modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/AshIndigo/Storage_Cabinet/issues"

[[mods]]
modId="storagecabinet"
version="${version}"
displayName="Storage Cabinet"
displayURL="https://www.curseforge.com/minecraft/mc-mods/storage-cabinet"
logoFile="icon.png"
credits=""
authors="AshIndigo, MoonlitLamps"
description='''
Adds multiple tiers of storage cabinets to Minecraft'''
[[dependencies.storagecabinet]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storagecabinet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
