modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="storagecabinet"
version="${version}"
displayName="Storage Cabinet"
displayURL="https://www.curseforge.com/minecraft/mc-mods/storage-cabinet"
issueTrackerURL="https://github.com/AshIndigo/Storage_Cabinet/issues"
logoFile="icon.png"
credits=""
authors="AshIndigo, MoonlitLamps, LotuxPunk"
description='''
Adds multiple tiers of storage cabinets to Minecraft'''
[[dependencies.storagecabinet]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storagecabinet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storagecabinet]]
    modId = "architectury"
    mandatory = true
    versionRange = "[3.1.44,)"
    ordering = "AFTER"
    side = "BOTH"